### PR TITLE
Drop Python v3.6

### LINKED ISSUE #27: Drop support for Python 3.6
See repobee/repobee#986

### PR DESCRIPTION
**Pull request by gauravagrwal**
Fix #27

### CODE REVIEW

**Review by slarse — CHANGES_REQUESTED** [review]
Hi @gauravagrwal,

Thanks for your contribution, the changes look good!

I realize however that I missed something in my original PR for the core repo, namely the `deploy` workflow (`.github/workflows/deploy.yml`). This also needs to be bumped to Python 3.7, could you see to that?

**Comment by gauravagrwal** [comment]
> 

ya, still it's using Python v3.6. should I also create PR for that one?

**Review by slarse — APPROVED** [review]
I probably need to get new glasses, you did update the deploy workflow here.

Thanks for your contribution :)

**Comment by slarse** [comment]
> ya, still it's using Python v3.6. should I also create PR for that one?

Yes that would be great.

**Pull request merged**
